functional and verbose parameters
jhrcook/mustashe pull request #17
Opened 2021-03-31 02:06 UTC by traversc

https://github.com/jhrcook/mustashe/issues/16

2021-04-06 13:22 UTC, jhrcook requested changes
I really like the additions and thank you for putting in a few tests for the new behavior. I left a few comments on the code, mainly minor styling that should be easy enough to quickly resolve. Thanks for the PR!

2021-04-06 13:22 UTC, jhrcook commented on R/stash.R
> +  }
Can you add explicit return calls? I think that would make the code a bit clearer and could potentially prevent some unexpected behavior (especially if new features are added).

2021-04-06 13:22 UTC, jhrcook commented on R/unstash.R
> +unstash <- function(var, verbose=TRUE) {
Can you put a space between the variables, values and equal sign? `verbose = TRUE`. Thanks!

2021-04-06 13:22 UTC, jhrcook commented on R/stash.R
> +  if(functional) {
Can you add explicit return calls? I think that would make the code a bit clearer and could potentially prevent some unexpected behavior (especially if new features are added).

2021-04-06 13:22 UTC, jhrcook commented on R/clear_stash.R
> +  if(verbose) message("Clearing stash.")
It's not the end of the world and you can leave it as is if you want, but I do prefer a space between the `if` and open ing parentheses and braces around the code block of an if statement: 

```r
if (verbose) { message("Clearing stash.") }
```

If you do make this change, can you update the other places, too? I'm thinking of adding a GH Action for styling the code in the future, so it really isn't a problem if you don't change this.

2021-04-07 07:03 UTC, traversc commented
Changes made. Should be good to go now :)

2021-04-07 10:40 UTC, jhrcook approved these changes
Looks great!

2021-04-07 10:40 UTC, merged